# Generated by Django 3.2.16 on 2022-12-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0005_auto_20221225_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.CharField(choices=[('2', 'two_seater_window'), ('2', 'two_seater_corner'), ('4', 'four_seater_window'), ('4', 'four_seater_middle'), ('6', 'six_seater_corner'), ('6', 'six_seater_window'), ('6', 'six_seater_middle')], max_length=12, unique_for_date=True),
        ),
    ]
