# Generated by Django 3.2.16 on 2022-12-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0007_alter_booking_party_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='four_seaters',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='six_seaters',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='two_seaters',
        ),
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.CharField(choices=[('two_seater_window', 'two_seater_window'), ('two_seater_corner', 'two_seater_corner'), ('four_seater_window', 'four_seater_window'), ('four_seater_middle', 'four_seater_middle'), ('six_seater_corner', 'six_seater_corner'), ('six_seater_window6', 'six_seater_window'), ('six_seater_middle', 'six_seater_middle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.CharField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], default='18:00', max_length=100),
        ),
    ]
