# Generated by Django 3.2.16 on 2022-12-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0008_auto_20221226_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.CharField(choices=[('two_seater_window', 'two_seater_window'), ('two_seater_corner', 'two_seater_corner'), ('four_seater_window', 'four_seater_window'), ('four_seater_middle', 'four_seater_middle'), ('six_seater_corner', 'six_seater_corner'), ('six_seater_window', 'six_seater_window'), ('six_seater_middle', 'six_seater_middle')], max_length=100),
        ),
    ]
